version: '3.7'

services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:${GRAPHQL_HTTP:-8000}'    # GraphQL HTTP
      - '8001:${GRAPHQL_WSS:-8001}'     # GraphQL WebSocket
      - '8020:${GRAPHQL_ADMIN:-8020}'   # JSON-RPC admin
      - '8030:${GRAPHQL_INDEXER:-8030}' # index node
      - '8040:${GRAPHQL_METRICS:-8040}' # metrics server
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: ${ETH_NETWORK}
      GRAPH_LOG: info
    networks:
      - ajna_test_network
  ipfs:
    image: ipfs/kubo:master-latest
    ports:
      - '5001:${GRAPHQL_IPFS:-5001}'
    networks:
      - ajna_test_network
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    expose:
      - '5432'
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    networks:
      - ajna_test_network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
networks:
  ajna_test_network:
    name: ajna_test_network